[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["dist/product-feedback-app-v2/**/*", "dist/product-feedback-app-v2/server/index.server.html"]
  
[[redirects]]
  from = "/assets/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "index.html"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "https://product-feedback-ssr.netlify.app/"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "https://product-feedback-ssr.netlify.app/index.html"
  to = "/.netlify/functions/server"
  status = 200

