[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["dist/product-feedback-app-v2/**/*"]

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200