[functions]
  included_files = ["dist/product-feedback-app-v2/server/*"]

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200