apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-product-feedback-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-feedback
  template:
    metadata:
      labels:
        app: product-feedback
    spec:
      containers:
        - name: nodejs
          image: creativefree/product-feedback-app:latest
          imagePullPolicy: 'Always'
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
