apiVersion: v1
kind: Service
metadata:
  name: product-feedback-app-svc
  labels: 
    app: product-feedback-frontend
    component: frontend
spec:
  selector:
    app: product-feedback-frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
