name: Build and Deploy with Helm
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Network Info
        run: |
          echo "IP Address:"
          curl -s ifconfig.me
          echo -e "\nFull route:"
          curl -s ifconfig.co/json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build ID
        id: tag
        run: echo "build_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            creativefree/product-feedback-app:latest
            creativefree/product-feedback-app:${{ steps.tag.outputs.build_id }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Add kubernetes configuration
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set Git user info
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

      - name: Update values.yaml with build tag
        run: |
          sed -i "s/tag: .*/tag: ${{ steps.tag.outputs.build_id }}/" deployment/helm-charts/product-feedback-app/values.yaml
          git add deployment/helm-charts/product-feedback-app/values.yaml
          git commit -m "Update image tag to ${{ steps.tag.outputs.build_id }}"
          git push origin main

      - name: Package and Push Helm Chart
        run: |
          helm package ./deployment/helm-charts/product-feedback-app
          helm push product-feedback-app-*.tgz oci://registry-1.docker.io/creativefree

      # - name: Deploy with Helm
      #   run: |
      #     helm upgrade product-feedback-app ./deployment/helm-charts/product-feedback-app \
      #       --set image.repository=creativefree/product-feedback-app \
      #       --set image.tag=${{ steps.tag.outputs.build_id }} \
      #       --namespace product-feedback
